Readme upgrade
uxpin-merge/uxpin-merge-boilerplate pull request #10
Opened 2019-02-22 23:29 UTC by marcintreder

Changes:
- link to Merge in the first section
- update of 'add new components' section
- update of JSX Preset section (JSON preset removed)
- added CI integration section

2019-02-25 08:23 UTC, michalstocki requested changes

2019-02-25 08:23 UTC, michalstocki commented on .circleci/config.yml
> -          name: "Run tests"
Why did you removed it?

2019-02-25 08:23 UTC, michalstocki commented on README.md
> +## Authoring JSX Presets
I think it's a bad idea to duplicate here the documentation of authoring the presets on CI configuration. IMHO we should put here only a link to the wiki documentation, otherwise it may be really hard to maintain the same documentation in different places.

2019-02-25 08:23 UTC, michalstocki commented on README.md
>  * You have to prepare presets for every component (temporary restrictions to be replaced by jsx presets)
This point should be corrected.
```suggestion
 * You have to prepare a default preset for every component
```

2019-02-25 08:23 UTC, michalstocki commented on README.md
>  ## Installation
I think the `## Tests` section is in a wrong place – I'd put it at the bottom of the readme, or at least under "Adding new components", as it's a detail important for repository maintainers, not a users experimenting with the technology.

2019-02-27 00:44 UTC, marcintreder commented on .circleci/config.yml
> -          name: "Run tests"
@michalstocki actually I was just meaning to change the build/docker part of the config. I don't think it makes sense to build this repository with our image and require credential to docker. This repo is meant to be forked by users

2020-12-16 02:43 UTC, closed without merging